branch-defaults:
  master:
    environment: longclaw-prod
    group_suffix: null
global:
  application_name: longclaw
  default_platform: Ruby 2.2 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git
