branch-defaults:
  develop:
    environment: production
    group_suffix: null
global:
  application_name: longclaw
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.2 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git
