development:
  google_client_id: 290954624013-nq59r23lvm30ehcl36ihk4h65dpc9rgu.apps.googleusercontent.com
  google_client_secret: 59VJa6QBgrJrIxmLwGLI1_l8
  mandrill_user_name: wcheung@contextsmith.com
  mandrill_api_key: QdWI4Lut5CI4AzaWfVFR2g
  csback_base_url: http://104.198.4.24:8888
#  csback_base_url: http://localhost:8888 # to use when running oathkeeper locally
#  csback_script_base_url: http://localhost:8888
  csback_script_base_url: http://104.198.4.24:8888
  mailchimp_api_key: 3cfa7a15477e3cbf657c20ab053c90b2-us13
  mailchimp_email_list_id: 0b8529ba9c
  salesforce_client_id: 3MVG9uudbyLbNPZN.LgCpo4h3qzBoUMWd0Rs_BnZBTRoBOie1OX3vELXocUZXdBq3mCaLY0TZNm2VhyQ7h7f0
  salesforce_client_secret: 3550523996344810646
  salesforce_sandbox_client_id: 3MVG982oBBDdwyHiqGsOXQz6wLLinqrWyAUQRz19HeA2MWIjX0iGa6PfE1LbD8x98nmuNETFb1_.0YyxfaIPo
  salesforce_sandbox_client_secret: 9048492794353274691
  basecamp_client_id: a708737faac642403a3b8fb000585ace49fd1935
  basecamp_client_secret: efd66e0c5c0ad9b43d5332646d994bf6eb4334a6
  basecamp_authorization_url: https://launchpad.37signals.com/authorization/new
  basecamp_token_url: https://launchpad.37signals.com/authorization/token
  basecamp_redirect_uri: http://localhost:3000/users/auth/37signals/callback
  BASE_URL: http://localhost:3000
  # tells the backend to limit e-mails to this number
  max_emails: 500
  encryption_key: ;?\x8E\xF4\xEC\xCB\xB7B\x17%\t\x9A\x8F\x01\x16y\xB4^\xBENo\x872\x03\xC3\xCCW\xE6\xB7\xCCDO
  fullcontact_api_key: Sq2rBc0BbT5ncMMqVAIGAdDsWsf5OgXo
  AZURE_APPLICATION_CLIENT_ID: 9a63b245-f4f3-4284-b71d-d040c85c6058
  AZURE_APPLICATION_CLIENT_SECRET: wgkwjSRA816##_+jbMNEC62
  super_admins: wcheung@contextsmith.com,will@context-smith.com,beders@contextsmith.com,klu@contextsmith.com,vluong@contextsmith.com,syong@contextsmith.com,chobbs@contextsmith.com,craig@context-smith.com,churst@contextsmith.com
  demo_opp_ids: f0798e45-bb46-4fe0-bc3e-adf6841aea08
  demo_contact_emails: charlie@plugandplaytechcenter.com,shelby@plugandplaytechcenter.com,peter@plugandplaytechcenter.com
  read_timeout: 300

test:
  google_client_id: 290954624013-o82ebj65g5l6knamiaa06jiu09epo2vk.apps.googleusercontent.com
  google_client_secret: L2Jt5992udy8Wk3k5oSJz11H
  mandrill_user_name: wcheung@contextsmith.com
  mandrill_api_key: QdWI4Lut5CI4AzaWfVFR2g
  mailchimp_api_key: 3cfa7a15477e3cbf657c20ab053c90b2-us13
  csback_base_url: https://104.198.4.24:8888
  csback_script_base_url: https://104.198.4.24:8888

production:
  # Change this back later!!!
  #google_client_id: 290954624013-rlf91qpur0fcqteie40prust5kiv9q5t.apps.googleusercontent.com
  #google_client_secret: ZbgIgjg6M2LhCUc2RIIOS-TQ
  google_client_id: 290954624013-o82ebj65g5l6knamiaa06jiu09epo2vk.apps.googleusercontent.com
  google_client_secret: L2Jt5992udy8Wk3k5oSJz11H
  AZURE_APPLICATION_CLIENT_ID: 83cc6ec7-6530-453f-9f98-8093f3dfc9ab
  AZURE_APPLICATION_CLIENT_SECRET: f2XbVMZsGjLdET0HcgdgfbU
  mailchimp_api_key: 3cfa7a15477e3cbf657c20ab053c90b2-us13
  mandrill_user_name: wcheung@contextsmith.com
  mandrill_api_key: wndqLIBQRJbIsA9S3bM-1w
  fullcontact_api_key: wsvCZ9dgkUQ5wEPS1BiZQm6k4zgcckBU
  csback_base_url: https://104.198.4.24:80
  csback_script_base_url: https://104.198.4.24:80