development:
  google_client_id: 9897521486-100gdg2aif8vkj52sebe1o22u1jo2h0a.apps.googleusercontent.com
  google_client_secret: kMCmqlzYF6pYp6L8-SIP8IGY
  mandrill_user_name: wcheung@contextsmith.com
  mandrill_api_key: QdWI4Lut5CI4AzaWfVFR2g
  csback_base_url: http://64.201.248.179:8887
  csback_script_base_url: http://64.201.248.179:8887
  csback_callback_base_url: http://24.130.10.244:3000
  salesforce_client_id: 3MVG9uudbyLbNPZN.LgCpo4h3qzBoUMWd0Rs_BnZBTRoBOie1OX3vELXocUZXdBq3mCaLY0TZNm2VhyQ7h7f0
  salesforce_client_secret: 3550523996344810646
  salesforce_url_instance: https://na30.salesforce.com
  TOKEN_KEY: 3MVG9uudbyLbNPZe1OX3vELXocUZBTRoBO

test:
  google_client_id: 9897521486-100gdg2aif8vkj52sebe1o22u1jo2h0a.apps.googleusercontent.com
  google_client_secret: kMCmqlzYF6pYp6L8-SIP8IGY
  mandrill_user_name: wcheung@contextsmith.com
  mandrill_api_key: QdWI4Lut5CI4AzaWfVFR2g
  csback_base_url: http://64.201.248.179:8888
  csback_script_base_url: http://64.201.248.179:8888
  csback_callback_base_url: https://guarded-refuge-6063.herokuapp.com
  salesforce_client_id: 3MVG9uudbyLbNPZOrXNoq6dS0sp5YD0kySrCYQeKobKUklay_Ao4ojqQZrwv1a4__doJ7S2MJ4uOiAiJn2ODL
  salesforce_client_secret: 17000624918700934
  salesforce_url_instance: https://na30.salesforce.com

production:
  google_client_id: 290954624013-rlf91qpur0fcqteie40prust5kiv9q5t.apps.googleusercontent.com
  google_client_secret: ZbgIgjg6M2LhCUc2RIIOS-TQ
  mandrill_user_name: wcheung@contextsmith.com
  mandrill_api_key: wndqLIBQRJbIsA9S3bM-1w
  csback_base_url: http://64.201.248.179:8889
  csback_script_base_url: http://64.201.248.179:8889
  csback_callback_base_url: https://app.contextsmith.com
  salesforce_client_id: 3MVG9uudbyLbNPZN.LgCpo4h3qzBoUMWd0Rs_BnZBTRoBOie1OX3vELXocUZXdBq3mCaLY0TZNm2VhyQ7h7f0
  salesforce_client_secret: 3550523996344810646
  salesforce_url_instance: https://na30.salesforce.com