development:
  google_client_id: 9897521486-100gdg2aif8vkj52sebe1o22u1jo2h0a.apps.googleusercontent.com
  google_client_secret: kMCmqlzYF6pYp6L8-SIP8IGY
  mandrill_user_name: wcheung@contextsmith.com
  mandrill_api_key: QdWI4Lut5CI4AzaWfVFR2g
  csback_base_url: http://64.201.248.178:8889
  csback_callback_base_url: http://24.130.10.244:3000

test:
  google_client_id: 9897521486-100gdg2aif8vkj52sebe1o22u1jo2h0a.apps.googleusercontent.com
  google_client_secret: kMCmqlzYF6pYp6L8-SIP8IGY
  mandrill_user_name: wcheung@contextsmith.com
  mandrill_api_key: QdWI4Lut5CI4AzaWfVFR2g
  csback_base_url: http://64.201.248.178:8889
  csback_callback_base_url: https://guarded-refuge-6063.herokuapp.com

production:
  google_client_id: 290954624013-rlf91qpur0fcqteie40prust5kiv9q5t.apps.googleusercontent.com
  google_client_secret: ZbgIgjg6M2LhCUc2RIIOS-TQ
  mandrill_user_name: wcheung@contextsmith.com
  mandrill_api_key: wndqLIBQRJbIsA9S3bM-1w
  csback_base_url: http://64.201.248.178:8889
  csback_callback_base_url: http://app.contextsmith.com