development:
  google_client_id: 9897521486-100gdg2aif8vkj52sebe1o22u1jo2h0a.apps.googleusercontent.com
  google_client_secret: kMCmqlzYF6pYp6L8-SIP8IGY
  mandrill_user_name: wcheung@contextsmith.com
  mandrill_api_key: QdWI4Lut5CI4AzaWfVFR2g
  csback_base_url: http://104.198.4.24:80
  csback_script_base_url: http://104.198.4.24:80
  salesforce_client_id: 3MVG9uudbyLbNPZN.LgCpo4h3qzBoUMWd0Rs_BnZBTRoBOie1OX3vELXocUZXdBq3mCaLY0TZNm2VhyQ7h7f0
  salesforce_client_secret: 3550523996344810646
  salesforce_url_instance: https://na30.salesforce.com
  salesforce_sandbox_client_id: 3MVG982oBBDdwyHiqGsOXQz6wLLinqrWyAUQRz19HeA2MWIjX0iGa6PfE1LbD8x98nmuNETFb1_.0YyxfaIPo
  salesforce_sandbox_client_secret: 9048492794353274691
  BASE_URL: http://localhost:3000

test:
  google_client_id: 9897521486-100gdg2aif8vkj52sebe1o22u1jo2h0a.apps.googleusercontent.com
  google_client_secret: kMCmqlzYF6pYp6L8-SIP8IGY
  mandrill_user_name: wcheung@contextsmith.com
  mandrill_api_key: QdWI4Lut5CI4AzaWfVFR2g
  csback_base_url: https://104.198.4.24:80
  csback_script_base_url: https://104.198.4.24:80

production:
  google_client_id: 290954624013-rlf91qpur0fcqteie40prust5kiv9q5t.apps.googleusercontent.com
  google_client_secret: ZbgIgjg6M2LhCUc2RIIOS-TQ
  mandrill_user_name: wcheung@contextsmith.com
  mandrill_api_key: wndqLIBQRJbIsA9S3bM-1w
  csback_base_url: https://104.198.4.24:80
  csback_script_base_url: https://104.198.4.24:80